name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
    - name: Create Django project
      run: docker-compose run web django-admin startproject proyecto .
    - name: Start Docker Compose
      run: docker-compose up -d
